### ISSUE TITLE
ef-themes-select empty until themes are loaded

### ISSUE THREAD

**Issue by iris-garcia** [protesilaos/ef-themes#2]
Hi Prot, 

First of all thank you for this amazing package, I love it.

The question I have is the following, if I just load the `ef-themes` like this:
```
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/ef-themes")
(require 'ef-themes)
```
When I call `ef-themes-select` there are no candidates, is this the intention?

If so, what is the best way to populate that list without having to load each theme during initialization?

Thank you.

**Comment by theherk** [comment]
I notice they are all present if I use `load-theme`, then afterwards, they are available in `ef-themes-select`.

**Comment by iris-garcia** [comment]
@theherk 
First call to `load-theme`:
![image](https://user-images.githubusercontent.com/3024945/185461760-7c1e4e46-cf7f-4a6a-b286-08ff4179b638.png)
Then a call to `ef-themes-select`
![image](https://user-images.githubusercontent.com/3024945/185461870-14f2ebd1-e67b-49ba-b79d-6157b57448da.png)

I think the themes are not added until they are actually loaded.

**Comment by protesilaos** [comment]
@iris-garcia I just pushed the change.  Yes, @theherk is correct in that `load-theme` would always recognise them, but the `ef-themes-select` didn't do that.

I have changed it now.  I believe it works properly.  Please give it a try.

I still plan to refine some of the internal functions in the interest of simplicity/correctness.  Though that will have to wait until tomorrow morning.

**Comment by iris-garcia** [comment]
Thank you for the quick response @protesilaos, I think the logic is good, but maybe you placed the enabling of themes function in the wrong place, I still don't see the candidates (It can also be an issue in my environment).

**Comment by protesilaos** [comment]
Mea culpa!  I only added it to one command, but not the other.  I pushed a change now.

**Comment by iris-garcia** [comment]
I have a suggestion, can I open a PR?

**Comment by protesilaos** [comment]
Yes, sure.  Though, if possible, keep the change below 15 lines.  Otherwise you need to assign copyright to the Free Software Foundation.

**Comment by iris-garcia** [comment]
I can confirm that this issue is fixed, happy to close this issue, however I see a new one with `ef-themes-load-random` which may be related to this one.

**Comment by protesilaos** [comment]
I just pushed commit `50be213` which should properly fix this issue.  Please let me know if this is the case.

Here is what I am loading at startup and both `ef-themes-load-random` and `ef-themes-select` do the right thing:

```elisp
(require 'ef-themes)

;; The `ef-themes' provide lots of themes.  I want to pick one at
;; random when I start Emacs: the `ef-themes-load-random' does just
;; that (it can be called interactively as well).  I just check with
;; GNOME to determine if the choice should be about a light or a dark
;; theme.
(if (string-match-p
     "dark"
     (shell-command-to-string "gsettings get org.gnome.desktop.interface color-scheme"))
    (ef-themes-load-random 'dark)
  (ef-themes-load-random 'light))

(define-key global-map (kbd "<f5>") #'ef-themes-select)
```

Simplified:

```elisp
(require 'ef-themes)

(ef-themes-load-random 'dark) ;; OR (ef-themes-load-random 'light)

(define-key global-map (kbd "<f5>") #'ef-themes-select)
```

**Comment by iris-garcia** [comment]
It works perfect now! Thank you @protesilaos, also for the suggestion on reading the current color-scheme of the DE to load dark or light themes.

**Comment by protesilaos** [comment]
Great!
